# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
  # 1 & 2. Install Maven & Java 21 via apt
  - pwsh: |
      sudo apt-get update
      sudo apt-get install -y maven openjdk-21-jdk
    displayName: 'Install Maven & Java 21'

  # 3. Build without tests
  - pwsh: |
      mvn clean package -DskipTests
    displayName: 'Maven Clean & Package'

  # Change working directory to automation-tests for subsequent steps
  - pwsh: |
      # no-op to set workingDirectory property
      Write-Host 'Switching context'
    workingDirectory: './automation-tests'
    displayName: 'Set Working Directory to automation-tests'

  # # 4. Run the JUnit Console Launcher - NEW
  # - pwsh: |
  #     java -cp target/automation-tests-1.0-SNAPSHOT.jar org.junit.platform.console.ConsoleLauncher --select-class io.automation.examples.suites.CalculatorTest --details verbose --config=junit.platform.reporting.open.xml.enabled=true --config=junit.platform.reporting.output.dir=target/test-results
  #   workingDirectory: './automation-tests'
  #   displayName: 'Run JUnit Console Launcher'

  # 4. Run the JUnit Console Launcher - LEGACY
  - pwsh: |
      java -cp target/automation-tests-1.0-SNAPSHOT.jar org.junit.platform.console.ConsoleLauncher --select-class io.automation.examples.suites.CalculatorTest --details verbose --reports-dir target/test-results
    workingDirectory: './automation-tests'
    displayName: 'Run JUnit Console Launcher'

  # 5. Publish JUnit test results
  - task: PublishTestResults@2
    condition: always()
    displayName: 'Publish JUnit Test Results'
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '*.xml'
      searchFolder: 'automation-tests/target/test-results'
      failTaskOnFailedTests: true
