# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
  # 1 & 2. Install Maven & Java 21 via apt
  - pwsh: |
      sudo apt-get update
      sudo apt-get install -y maven openjdk-21-jdk
    displayName: 'Install Maven & Java 21'

  # 3. Build without tests
  - pwsh: |
      mvn clean package -DskipTests
    displayName: 'Maven Clean & Package'

  # Change working directory to automation-tests for subsequent steps
  - pwsh: |
      # no-op to set workingDirectory property
      Write-Host 'Switching context'
    workingDirectory: './automation-tests'
    displayName: 'Set Working Directory to automation-tests'

  # # 4. Run the JUnit Console Launcher - NEW
  # - pwsh: |
  #     java -cp target/automation-tests-1.0-SNAPSHOT.jar org.junit.platform.console.ConsoleLauncher --select-class io.automation.examples.suites.CalculatorTest --details verbose --config=junit.platform.reporting.open.xml.enabled=true --config=junit.platform.reporting.output.dir=target/test-results
  #   workingDirectory: './automation-tests'
  #   displayName: 'Run JUnit Console Launcher'

  # 4. Run the JUnit Console Launcher - LEGACY
  - pwsh: |
      java -cp target/automation-tests-1.0-SNAPSHOT.jar org.junit.platform.console.ConsoleLauncher --select-class io.automation.examples.suites.CalculatorTest --details verbose --reports-dir target/test-results
    workingDirectory: './automation-tests'
    displayName: 'Run JUnit Console Launcher'

  # 5. Publish JUnit test results
  - task: PublishTestResults@2
    condition: always()
    displayName: 'Publish JUnit Test Results'
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '*.xml'
      searchFolder: 'automation-tests/target/test-results'
      failTaskOnFailedTests: true

  # 6. Install Allure CLI via shell
  - pwsh: |
      sudo apt-get update
      sudo apt-get install -y wget unzip
      # Download Allure 2.21.0
      wget https://github.com/allure-framework/allure2/releases/download/2.21.0/allure-2.21.0.zip -O allure.zip
      unzip allure.zip -d allure
      sudo mv allure/bin/allure /usr/local/bin/
      sudo chmod +x /usr/local/bin/allure
    workingDirectory: './automation-tests'
    displayName: 'Install Allure CLI'
    condition: always()

  # 7. Generate Allure report from allure-results
  - pwsh: |
      mkdir -p target/allure-report
      allure generate target/allure-results -o target/allure-report --clean
    workingDirectory: './automation-tests'
    displayName: 'Generate Allure Report'

  # 8. Publish Allure report artifact
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Allure Report Artifact'
    inputs:
      PathtoPublish: 'automation-tests/target/allure-report'
      ArtifactName: 'AllureReport'
      publishLocation: 'Container'
